// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEq87qm6-LafPau08qaDAM6ZRxC90JkFk',
    appId: '1:955957542219:web:e95e7709d40cc2c0967cce',
    messagingSenderId: '955957542219',
    projectId: 'aio-plus-ai',
    authDomain: 'aio-plus-ai.firebaseapp.com',
    storageBucket: 'aio-plus-ai.appspot.com',
    measurementId: 'G-RE15H1VS0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAAVfvN3nQH1QLnSqfPqmbgND4xzkshWE',
    appId: '1:955957542219:android:a899d0a6fc13de39967cce',
    messagingSenderId: '955957542219',
    projectId: 'aio-plus-ai',
    storageBucket: 'aio-plus-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw3mEkOX6BrYc0O48wgJA0mqS-tWaI5Bg',
    appId: '1:955957542219:ios:6921031f21185281967cce',
    messagingSenderId: '955957542219',
    projectId: 'aio-plus-ai',
    storageBucket: 'aio-plus-ai.appspot.com',
    iosBundleId: 'com.example.aioplusai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw3mEkOX6BrYc0O48wgJA0mqS-tWaI5Bg',
    appId: '1:955957542219:ios:6921031f21185281967cce',
    messagingSenderId: '955957542219',
    projectId: 'aio-plus-ai',
    storageBucket: 'aio-plus-ai.appspot.com',
    iosBundleId: 'com.example.aioplusai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEq87qm6-LafPau08qaDAM6ZRxC90JkFk',
    appId: '1:955957542219:web:01c713160cb6a271967cce',
    messagingSenderId: '955957542219',
    projectId: 'aio-plus-ai',
    authDomain: 'aio-plus-ai.firebaseapp.com',
    storageBucket: 'aio-plus-ai.appspot.com',
    measurementId: 'G-SV7DWZSZH8',
  );
}
